/*
 * Generated by tutor-mfe for {{ current_mfe }}.
 *
 * Frontend-base counterpart of the legacy env.config.jsx.
 */

{{ patch("mfe-env-config-buildtime-imports") }}

import { DIRECT_PLUGIN, IFRAME_PLUGIN, PLUGIN_OPERATIONS } from '@openedx/frontend-plugin-framework';

function addPlugins(config, slot_name, plugins) {
  if (slot_name in config.pluginSlots === false) {
    config.pluginSlots[slot_name] = {
      keepDefault: true,
      plugins: []
    };
  }
  config.pluginSlots[slot_name].plugins.push(...plugins);
}

{{- patch("mfe-env-config-buildtime-definitions") }}

function setConfig() {
  const config = {
    pluginSlots: {},
  };

  {{- patch("mfe-env-config-runtime-definitions") }}

  {%- for slot_name, plugin_config in iter_frontend_compat_slots(current_mfe) %}
  addPlugins(config, '{{ slot_name }}', [{{ plugin_config }}]);
  {%- endfor %}

  {{- patch("mfe-env-config-runtime-final") }}

  return config;
}

export default setConfig;
